import db from '../config/db.js';
import Event from '../models/Event.js';
/**
 * Repository responsible for database operations related to events.
 * It contains SQL queries and converts database rows into Event model objects.
 */
export default class EventRepository {
  async findByUrl(eventUrl) {
    const sql = `
      SELECT *
      FROM events
      WHERE url = ?
      LIMIT 1
    `;

    const [rows] = await db.execute(sql, [eventUrl]);

    if (rows.length === 0) {
      return null;
    }

    return Event.fromDatabaseRow(rows[0]);
  }
  /**
   * Finds upcoming events by location.
   *
   * @param {string} location Event location.
   * @returns {Promise<Event[]>} List of upcoming events for the given location.
   */
  async findByLocation(location) {
    const sql = `
    SELECT *
    FROM events
    WHERE date >= CURDATE()
    AND location = ?
    ORDER BY date ASC
  `;

    const [rows] = await db.execute(sql, [location]);

    return rows.map((row) => Event.fromDatabaseRow(row));
  }
  /**
   * Finds one event by its ID.
   *
   * @param {number} id Event ID.
   * @returns {Promise<Event|null>} Event object if found, otherwise null.
   */
  async findById(id) {
    const sql = `
    SELECT *
    FROM events
    WHERE id = ?
    LIMIT 1
  `;

    const [rows] = await db.execute(sql, [id]);

    if (rows.length === 0) {
      return null;
    }

    return Event.fromDatabaseRow(rows[0]);
  }
  /**
   * Finds upcoming events by event type.
   *
   * @param {string} type Event type/category.
   * @returns {Promise<Event[]>} List of upcoming events for the given type.
   */
  async findByType(type) {
    const sql = `
    SELECT *
    FROM events
    WHERE date >= CURDATE()
    AND type = ?
    ORDER BY date ASC
  `;

    const [rows] = await db.execute(sql, [type]);

    return rows.map((row) => Event.fromDatabaseRow(row));
  }
  /**
   * Finds all upcoming events.
   *
   * @returns {Promise<Event[]>} List of upcoming events.
   */
  async findAll() {
    const sql = `
      SELECT *
      FROM events
      WHERE date >= CURDATE()
      ORDER BY date DESC
    `;

    const [rows] = await db.execute(sql);

    return rows.map((row) => Event.fromDatabaseRow(row));
  }
  /**
   * Saves a new event to the database.
   * The ID is generated by the database because it is auto-incremented.
   *
   * @param {Event} event Event object to save.
   * @returns {Promise<number>} Inserted event ID.
   */
  async save(event) {
    const sql = `
      INSERT INTO events (
        url,
        title,
        content,
        location,
        date,
        price,
        type
      )
      VALUES (?, ?, ?, ?, ?, ?, ?)
    `;

    const [result] = await db.execute(sql, [
      event.url,
      event.title,
      event.content,
      event.location,
      event.date,
      event.price,
      event.type,
    ]);

    return result.insertId;
  }
  /**
   * Increases the like count of one event by 1.
   *
   * @param {number} id Event ID.
   * @returns {Promise<boolean>} True if an event was updated, otherwise false.
   */
  async increaseLikesById(id) {
    const sql = `
    UPDATE events
    SET likes = likes + 1
    WHERE id = ?
  `;
    const [result] = await db.execute(sql, [id]);
    return result.affectedRows > 0;
  }
  /**
   * Finds unique locations that currently have upcoming events.
   * Used to build dynamic HATEOAS filter links.
   *
   * @returns {Promise<string[]>} List of unique location names.
   */
  async findUniqueLocations() {
    const sql = `
    SELECT DISTINCT location
    FROM events
    WHERE location IS NOT NULL
      AND date >= CURDATE()
    ORDER BY location ASC
  `;

    const [rows] = await db.execute(sql);

    return rows.map((row) => row.location);
  }
  /**
   * Finds unique event types that currently have upcoming events.
   * Used to build dynamic HATEOAS filter links.
   *
   * @returns {Promise<string[]>} List of unique event types.
   */
  async findUniqueTypes() {
    const sql = `
    SELECT DISTINCT type
    FROM events
    WHERE type IS NOT NULL
     AND date >= CURDATE()
    ORDER BY type ASC
  `;

    const [rows] = await db.execute(sql);

    return rows.map((row) => row.type);
  }
}
